# BIRD 2 — vetor de distância (RIP), roteador 2
log stderr all;
router id 0.0.0.0;              # TAREFA: dois roteadores não podem ter a mesma
                                # identidade. Ponha aqui o endereço de r2 no
                                # segmento B.

protocol device { }
protocol direct { ipv4; interface "eth*"; }
protocol kernel { ipv4 { export all; }; learn; }

protocol rip {
  ipv4 { import all; export all; };
  interface "*" { };
}
